MONGODB_HOST: mongodb-{{ env }}-dsoaws.fun
REDIS_HOST: redis-{{ env }}-dsoaws.fun
CATALOGUE_HOST: catalogue-{{ env }}-dsoaws.fun
CART_HOST: cart-{{ env }}-dsoaws.fun
USER_HOST: user-{{ env }}-dsoaws.fun
RABBITMQ_HOST: rabbitmq-{{ env }}-dsoaws.fun
MYSQL_HOST: mysql-{{ env }}-dsoaws.fun
SHIPPING_HOST: shipping-{{ env }}-dsoaws.fun
PAYMENT_HOST: payment-{{ env }}-dsoaws.fun