$ANSIBLE_VAULT;1.1;AES256
32653337366630313962616236343364656434383262326264633839363864313039353236316335
3862393533663363663430376262356533643834646464340a663033646639653532326435363264
32666234336333666465346339636137316430373432373934653831343930326366613932353030
6338636264623339630a643334653738376365643330313861373634663837353261323165303530
32386336343230353734303136313131653363383238313462353764336663643061