# syntax FOR https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/import_role_module.html

- name: app setup
  ansible.builtin.import_role:
    name: for-common
    tasks_from: app-setup.yaml

# THE ABOVE VARAKU RUN CHESTE ansible-playbook -i inventory.ini main.yaml -e "component=catalogue" 

# sess-48 for terraform 
# changed this as part of latest python3-devel from repos have upgraded openssl-libs but other openssl packages are old in AMI, so mismatch occured. we are upgrading before installing python or after
- name: upgrade openssl packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
  - openssl
  - openssl-libs
  - openssh
  - openssh-server
  - openssh-clients


- name: app setup
  ansible.builtin.import_role:
    name: for-common
    tasks_from: python.yaml # for-common lo vunna code ni call chstunnam 

- name: system setup
  ansible.builtin.import_role:
    name: for-common
    tasks_from: system-setup.yaml

